### ISSUE TITLE
Add commands/functions/types to stacks addon

### ISSUE THREAD

**Issue by MicaiahReid** [txtx/txtx#29]
Clarity Types:
- [x] uint
- [x] int
- [x] bool
- [x] principal
- [x] ascii
- [x] utf8
- [x] list
- [x] buffer
- [x] tuple
- [x] optional
- [x] response
- [x] clarity value (any of above)

Functions:
- [x] uint
- [x] int
- [x] bool
- [x] principal
- [x] ascii
- [x] utf8
- [x] list
- [x] buffer
- [x] tuple
- [x] optional
- [x] response
- [x] get account balance
- [x] get account nonce
- [ ] decode call contract
- [ ] decode transfer
- [ ] decode contract deploy (can decodes just be decode transaction?)
- [x] broadcast transaction
- [x] poll for inclusion in block

Commands:
- [x] Encode contract call
- [x] Encode transfer
- [x] Encode contract deployment
- [x] Read from directory
- [x] Sign transaction
