### ISSUE TITLE
Make txtx installable

### ISSUE THREAD

**Issue by MicaiahReid** [txtx/txtx#31]
- [x] Implement CI to build project on all targets
  - [x] Upload binaries for web-ui
  - [x] Fix build.rs to download built web ui for ci
  - [x] Fix build.rs to bundle web ui as part of the project
- [x] Host binaries

Eventually
- [x] Homebrew
- [ ] Winget
- [x] Snapcraft
